#!/usr/bin/env ruby
require 'tmpdir'
require 'timeout'
require 'fileutils'

BUILD_TIMEOUT_IN_SECONDS = 2400
TEST_INFRA_PATH = File.expand_path File.dirname(__FILE__)
BUILD_TO_RUN_PATH = Dir.pwd

def sh(cmd)
  ok = system(cmd)
  raise RuntimeError unless ok
  ok
end


tmpdir = Dir.mktmpdir
FileUtils.copy("#{TEST_INFRA_PATH}/create_vagrant_and_run_test.sh", tmpdir)
FileUtils.copy("#{TEST_INFRA_PATH}/start_warden.sh", tmpdir)
puts "Running vagrant in a temporary folder: #{tmpdir}"
Dir.chdir(tmpdir) do
  begin
    Timeout.timeout(BUILD_TIMEOUT_IN_SECONDS) do
      sh("bash -x ./create_vagrant_and_run_test.sh '#{BUILD_TO_RUN_PATH}' '#{TEST_INFRA_PATH}'")
    end
  rescue Timeout
    puts 'Build took too long, killing the VM'
  ensure
    if ENV["NODESTROY"]
      puts "Skipping vagrant destroy"
    else
      sh('vagrant destroy --force')
      puts 'Destroyed the vagrant box, vagrant status: '
    end
    sh('vagrant status')
  end
end
