#!/usr/bin/env ruby
require 'tmpdir'
require 'timeout'
require 'fileutils'

BUILD_TIMEOUT_IN_SECONDS = 2400

def sh(cmd)
  ok = system(cmd)
  raise RuntimeError unless ok
  ok
end

Dir.mktmpdir do |tmpdir|
  FileUtils.copy("create_vagrant_and_run_test.sh", tmpdir)
  FileUtils.copy("start_warden.sh", tmpdir)
  puts "Running vagrant in a temporary folder: #{tmpdir}"
  Dir.chdir(tmpdir) do
    begin
      Timeout.timeout(BUILD_TIMEOUT_IN_SECONDS) do
        sh("bash -x ./create_vagrant_and_run_test.sh")
      end
    rescue Timeout
      puts 'Build took too long, killing the VM'
    ensure
      sh('vagrant destroy --force')
      puts 'Destroyed the vagrant box, vagrant status: '
      sh('vagrant status')
    end
  end
end
