#!/bin/bash -eux

echo ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC/xnFbY6TjmMEYVekv+qtgTQxtBnnAfWD7sKWFHQ0Mj/aNL5/O+Dv3WyYo/8n4ZR8ku/OEyG1AefuGT9+FHqK+RwrWdOmocbtGZMGS7VPNp7WzjHFNOdn8f/xZNj/rLG3xLL/HRUtG9ATs7lJmQobMfKveU7goRdYnY37/E0hlRci7gliXhU4dEwUWlmh76guHgAs8ShYnsp1cZLrLAxjavPLr1oIzjP73JxaCojIa3Alh3Sl0+PiwqTWsLn2xkteFcDS+yhYt3pUFANy/REFvABpNSXB+T8GBB7azqwJ2odUdh73XbijsFQfZr2U5EI5wnHzUsHpRLPPpJMfsYJoV id_rsa_warden-test-infrastructure > ~vagrant/.ssh/authorized_keys

